"""Athanor ingestion — pull profile/exemplar/preliminary-data from raw inputs."""
from .profile import ProfileSource, ingest_profile
from .grant import (
    ExemplarGrant,
    GrantBudget,
    GrantStructure,
    GrantStyle,
    GrantInstitutional,
    MergedGrantContext,
    ingest_grant,
    merge_with_defaults,
)
from .funder_profiles import FunderProfile, get_profile, list_profiles, PROFILES
from .resources import (
    ResearchResources,
    ComputeResources,
    DataResources,
    InstrumentResources,
    PersonnelResources,
    SoftwareResources,
    InstitutionalResources,
    ingest_resources,
    default_academic_resources,
    default_biomedical_resources,
    default_ai_ml_resources,
    default_observational_astro_resources,
    default_physical_sciences_resources,
    default_lab_chemistry_resources,
    default_social_sciences_resources,
    default_engineering_resources,
    merge_resources_with_defaults,
    merge_exemplar_facilities_into_resources,
    get_domain_defaults,
    RESEARCH_DOMAINS,
    DOMAIN_DEFAULTS,
)

__all__ = [
    "ProfileSource",
    "ingest_profile",
    "ExemplarGrant",
    "GrantBudget",
    "GrantStructure",
    "GrantStyle",
    "GrantInstitutional",
    "MergedGrantContext",
    "ingest_grant",
    "merge_with_defaults",
    "FunderProfile",
    "get_profile",
    "list_profiles",
    "PROFILES",
    "ResearchResources",
    "ComputeResources",
    "DataResources",
    "InstrumentResources",
    "PersonnelResources",
    "SoftwareResources",
    "InstitutionalResources",
    "ingest_resources",
    "default_academic_resources",
    "default_biomedical_resources",
    "default_ai_ml_resources",
    "default_observational_astro_resources",
    "default_physical_sciences_resources",
    "default_lab_chemistry_resources",
    "default_social_sciences_resources",
    "default_engineering_resources",
    "merge_resources_with_defaults",
    "merge_exemplar_facilities_into_resources",
    "get_domain_defaults",
    "RESEARCH_DOMAINS",
    "DOMAIN_DEFAULTS",
]
