"""
Athanor Mock LLM Client.

Drop-in replacement for the LLM client that returns canned responses
keyed by schema type.  Activated via:

    llm_provider = "mock"  in athanor_config.toml

The mock is intentionally *structurally correct* but uses placeholder
prose so that it's obvious the output came from mock data.  This allows
full pipeline tests without hitting any real LLM API.
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, Optional, Type

from .config_loader import config
from .types import LLMTextResponse


def is_mock_enabled() -> bool:
    """Check whether mock mode is active."""
    if os.getenv("ATHANOR_MOCK_LLM", "").strip() in ("1", "true", "yes"):
        return True
    return (config.llm_provider or "").lower() == "mock"


# ---------------------------------------------------------------------------
# Canned text responses keyed by agent name patterns
# ---------------------------------------------------------------------------

_CANNED_TEXT: Dict[str, str] = {
    "profiler": (
        "Dr. Mock Researcher is a leading expert in computational astrophysics "
        "at Mock University. Their work focuses on large-scale structure formation "
        "and dark matter simulations. Key publications include studies on void "
        "statistics and cosmic web topology. Available resources include HPC cluster "
        "access and collaborations with major survey teams."
    ),
    "proponent": (
        "The proposed hypothesis represents a significant advance in understanding "
        "the phenomenon. Prior work has established the foundational observations, "
        "but no study has directly tested this specific mechanism. The approach is "
        "computationally feasible with existing resources and could yield results "
        "within 18 months."
    ),
    "antagonist": (
        "While the hypothesis is interesting, several concerns warrant attention: "
        "(1) The proposed mechanism may be degenerate with alternative explanations. "
        "(2) The sample size required for statistical significance is unclear. "
        "(3) Systematic effects from instrument calibration have not been addressed."
    ),
    "judge": json.dumps({
        "novelty_score": 4,
        "novelty_rationale": "[MOCK] The hypothesis addresses a known gap.",
        "plausibility_score": 3,
        "plausibility_rationale": "[MOCK] Mechanism is plausible but unverified.",
        "falsifiability_score": 4,
        "is_falsifiable": True,
        "falsifiability_rationale": "[MOCK] Clear predictions can be tested.",
        "executability_score": 4,
        "executability_rationale": "[MOCK] Resources are available.",
        "impact_score": 3,
        "impact_rationale": "[MOCK] Moderate impact on the field.",
        "is_safe": True,
        "safety_rationale": "[MOCK] No ethical concerns.",
        "unresolved_issues": ["[MOCK] Sample size needs clarification"],
        "final_score_avg": 3.6,
        "recommendation": "PROCEED",
        "verdict_summary": "[MOCK] The hypothesis is sound and worth pursuing.",
        "feedback_summary": "[MOCK] Address sample size and systematics."
    }),
    "drafter": (
        "[MOCK] Research Plan Draft:\n\n"
        "Phase 1: Data Collection (Months 1-6)\n"
        "- Task 1.1: Acquire observational data from public archives\n"
        "- Task 1.2: Run baseline simulations for comparison\n\n"
        "Phase 2: Analysis (Months 7-12)\n"
        "- Task 2.1: Apply statistical methods to observational sample\n"
        "- Task 2.2: Compare simulation outputs with observations\n\n"
        "Phase 3: Synthesis (Months 13-18)\n"
        "- Task 3.1: Interpret results in context of hypothesis\n"
        "- Task 3.2: Prepare manuscript for publication"
    ),
    "writer": (
        "[MOCK] Grant Proposal Section:\n\n"
        "# Project Summary\n\n"
        "This proposal seeks to investigate the fundamental mechanisms underlying "
        "the observed phenomenon through a combination of computational modeling "
        "and observational analysis. The project leverages existing institutional "
        "resources and established collaborations to deliver results within the "
        "proposed timeline.\n\n"
        "# Intellectual Merit\n\n"
        "The proposed work addresses a critical gap in current understanding."
    ),
    "default": (
        "[MOCK] This is a placeholder response from the Athanor Mock LLM. "
        "The actual content would be generated by the configured LLM provider."
    ),
}


def _get_canned_text(agent_name: str) -> str:
    """Return canned text for the given agent name."""
    key = agent_name.lower()
    for pattern, text in _CANNED_TEXT.items():
        if pattern in key:
            return text
    return _CANNED_TEXT["default"]


class StructuredMockRunner:
    """Mock equivalent of StructuredLLMRunner."""

    def __init__(self, parent: "MockLLMClient", schema: Type[Any]):
        self.parent = parent
        self.schema = schema

    def run(self, input_data: Any, config: Optional[Any] = None, timeout: Optional[int] = None, **kwargs: Any) -> Any:
        return self.parent._mock_structured(self.schema)


class MockLLMClient:
    """Mock LLM client that returns canned responses without API calls."""

    def __init__(self, name: str = "MockAgent", verbose: bool = False, model_name: Optional[str] = None, **kwargs):
        self.name = name
        self.verbose = verbose
        self.model_name = model_name or "mock"

    @staticmethod
    def _mock_usage() -> Dict[str, int]:
        return {
            "prompt_tokens": 100,
            "completion_tokens": 200,
            "total_tokens": 300,
            "input_tokens": 100,
            "output_tokens": 200,
        }

    def _mock_structured(self, schema: Type[Any]) -> Any:
        """Return a structurally valid instance of the given Pydantic schema."""
        schema_name = schema.__name__ if hasattr(schema, "__name__") else str(schema)

        # Try to find a canned JSON for this specific schema
        canned_key = schema_name.lower()
        for pattern, text in _CANNED_TEXT.items():
            if pattern in canned_key:
                try:
                    if hasattr(schema, "model_validate_json"):
                        return schema.model_validate_json(text)
                except Exception:
                    pass

        # Fallback: construct with defaults
        if hasattr(schema, "model_construct"):
            try:
                return schema.model_construct()
            except Exception:
                pass

        # Last resort: try empty construction
        try:
            return schema()
        except Exception:
            raise RuntimeError(
                f"MockLLMClient cannot construct {schema_name}. "
                f"Add a canned response for this schema in mock_llm.py."
            )

    def run_text(self, input_data: Any, config: Optional[Any] = None, timeout: Optional[int] = None, **kwargs: Any) -> LLMTextResponse:
        """Return canned text response."""
        if self.verbose:
            print(f"    [MOCK LLM] {self.name} returning canned text response.")
        return LLMTextResponse(
            content=_get_canned_text(self.name),
            usage_metadata=self._mock_usage(),
        )

    def structured(self, schema: Type[Any]) -> StructuredMockRunner:
        """Return a mock structured runner."""
        return StructuredMockRunner(self, schema)

